# Generated by Django 4.1.6 on 2023-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_created_date_customuser_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
